services:
  face-ai-service:
    image: face-ai-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face-ai-service
    ports:
      - "8000:8000"
    volumes:
      - ./app/reference:/app/reference  # mount face image storage
    command: uvicorn main:app --host 0.0.0.0 --port 8000
